#!/bin/sh
exec s6-setuidgid jetson \
    python3 -m wyoming_faster_whisper \
        --uri tcp://0.0.0.0:10300 \
        --model "${WHISPER_MODEL:-base.en}" \
        --data-dir /models/whisper \
        --download-dir /models/whisper \
        --language en