#!/bin/sh
exec s6-setuidgid jetson \
    python3 -m wyoming_piper \
        --uri tcp://0.0.0.0:10200 \
        --voice "${PIPER_VOICE:-en_US-ryan-medium}" \
        --data-dir /models/piper \
        --download-dir /models/piper